folders:
  input_folder: input
  output_folder: output
  sqlite_db: output.sqlite
  sqlite_table: financial_data

files_csv:
  source_financial_indicators: financial_indicators.csv
  source_largest_companies: largest_companies.csv
  merged_table: merged_table.csv

files_sql:
  source_financial_indicators: financial_indicators
  source_largest_companies: largest_companies
  merged_table: merged_table

largest_company_dataset:
  Rank: Rank

etl_main_parameters:
  to_sqlite: false ##voir pourquoi c'est faux
  drop_all_tables: true
  to_csv: true

columns:
  largest_companies:
    Rank : Rank
    Company : Company
    Industry : Industry
    Revenue in (USD Million) : Revenue
    Net Income in (USD Millions) : Net_Income
    Total Assest in (USD Millions) : Total_Asset
    Headquarters: Country

  largest_companies_aggregated:
    Headquarters: Country
    Revenue: Mean_Revenue
    Net_Income: Mean_Income
    Total_Asset: Mean_Total_Asset

rename_merged_table:
  Headquarters: Country
  Mean Revenue in (USD Million): Mean_Revenue
  Mean Net Income in (USD Millions): Mean_Income
  Mean Total Asset in (USD Millions): Mean_Total_Asset
  Interest Rate (%): Interest_Rate_Pct
  Inflation Rate (%): Inflation_Rate_Pct
  Stock Market Capitalization (% of GDP): Stock_market_Capitalization
  Banking Sector Assets (% of GDP): Banking_Sector_Asset
  Corporate Tax Rate (%): Corporate_Tax_Rate
  GDP (USD Trillions): GDP_USD_Trillion

drop_columns_largest_companies:
  - Rank

drop_columns_merged_table:
  - Country

countries_financial_summary_table:
  revenue_to_gdp: Revenue to GDP (%)
  real_interest_rate: Real Interest Rate (%)
  average_contrib_to_pub_fin: Average Contribution to Public Finances (% of GDP)
  average_roa: Average ROA

firms_financial_summary_table:
  asset_efficiency: Asset Efficiency
  return_on_assets: Return on Assets



data:
  Financial Summary Table: Financial Summary Table
  Firms Summary Table:  Firms Summary Table

streamlit:
  settings:
    page_title: "J'ai sommeil"
    initial_sidebar_state: collapsed

  widgets:
    start_button:
      label: 'inaf'
    ticker_radio:
      label: Get data
      items: ['a voir', 'a voir2', 'a voir3', 'a voir4']
    start_label:
      label: Vas-y
    expander_data:
      label: YAS
    widgets:
    title:
      label: OUF

