folders:
  input_folder: input
  output_folder: output
  database_path: final_output.sqlite

files_csv:
  source_financial_indicators: financial_indicators.csv
  source_largest_companies: largest_companies.csv
  merged_table: merged_table.csv

export_final_results:
  financial_summary_stat: country_financial_summary
  firms_summary_stat: firms_financial_stat

logger:
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

columns:
  # raw dataset
  largest_companies:
    Rank : rank
    Company : company
    Industry : industry
    Revenue in (USD Million) : revenue_usd_millions
    Net Income in (USD Millions) : net_income_millions
    Total Assest in (USD Millions) : total_asset_millions
    Headquarters: country

  largest_companies_aggregated:
    # aggregated dataset
    country: country
    revenue_usd_millions: mean_revenue
    net_income_millions: mean_income
    total_asset_millions: mean_total_asset

# for the export to the SQLite database
data:
  country_financial_summary: Financial Summary Table
  firms_financial_stat:  Firms Summary Table

financial_indicators:
  # raw dataset
  Country: country
  Interest Rate (%): interest_rate_pct
  Inflation Rate (%): inflation_rate_pct
  Banking Sector Assets (% of GDP): banking_sector_assets_pct
  Stock Market Capitalization (% of GDP): stock_market_cap_pct
  Corporate Tax Rate (%): corporate_tax_rate
  GDP (USD Trillions): gdp_usd_trillion

rename_merged_table:
  # merged dataset
  Headquarters: country
  Mean Revenue in (USD Million): mean_revenue
  Mean Net Income in (USD Millions): mean_income
  Mean Total Asset in (USD Millions): mean_total_asset
  Interest Rate (%): interest_rate_pct
  Inflation Rate (%): inflation_rate_pct
  Stock Market Capitalization (% of GDP): stock_market_capitalization
  Banking Sector Assets (% of GDP): banking_sector_asset
  Corporate Tax Rate (%): corporate_tax_rate
  GDP (USD Trillions): gdp_usd_trillion

drop_columns_largest_companies:
  - rank

drop_columns_merged_table:
  - country

# final output
countries_financial_summary_table:
  revenue_to_gdp: Revenue to GDP (%)
  real_interest_rate: Real Interest Rate (%)
  average_contrib_to_pub_fin: Average Contribution to Public Finances (% of GDP)
  average_roa: Average ROA

# final output
firms_financial_summary_table:
  company: Company
  asset_efficiency: Asset Efficiency
  return_on_assets: Return on Assets

# streamlit parameters
streamlit:
  settings:
    page_title: Groupe P
    layout: 'wide'
    initial_sidebar_state: auto
    menu_items:
      Get Help: null
      Report a bug: null
      About: Groupe P

  widgets:
    selected_dataset:
      label: Choix des données
    options:
      Données par entreprise:
       - Top 10 ROA
       - ROA vs Efficacité des actifs
      Données par pays:
       - Contribution vs ROA
       - Matrice de corrélation macro
    select_box:
      label: Choix du graphique
    header:
      label: Visualisation de données
      divider: blue
    start_button:
      label: Afficher
    column:
      vertical_alignment: bottom
    expander:
      donnees_par_entreprise: Tableau - Données par entreprise
      donnees_par_pays: Tableau - Données par pays
    slider:
      roa: Filtrage par ROA (%)
      efficiency: Filtrage par efficacité des actifs (%)


#plots
plot_roa_vs_efficiency:
  title: Rentabilité vs Efficacité des actifs (entreprises)
  labels:
    Asset Efficiency: Efficacité des Actifs
    Return on Assets: ROA (%)
  markdown: |
    Ici, nous explorons la relation entre la rentabilité des entreprises (ROA) et leur efficacité d’utilisation des actifs.
    Le **ROA est assez dispersé** : certaines entreprises génèrent beaucoup de rentabilité pour chaque actif, d’autres beaucoup moins.
    En revanche, **l’efficacité des actifs est très liée au secteur** : Les **banques** se concentrent autour de 0,5 (beaucoup d’actifs, marges faibles), tandis que les **assureurs ou sociétés d’investissement** montent à 2 ou 3 (actifs plus légers, rendement plus fort).
    Cela suggère que **le modèle économique joue un rôle structurant** : on ne peut pas comparer tous les secteurs sur ces deux axes sans contexte.


plot_top10_roa:
  x_axis: company
  y_axis: Return on Assets
  title: Top 10 entreprises par ROA
  col_y: Return on Assets
  labels:
    company: Company
    Return on Assets: ROA (%)
  markdown: |
    Ce graphique montre quelles entreprises utilisent le mieux leurs actifs pour générer du profit. Il est très pertinent pour détecter les modèles de gestion les plus performants.
    On voit que des sociétés d’investissement comme Brookfield, Freddie Mac ou Morgan Stanley dominent.


plot_contribution_vs_roa:
  text: country
  title: ROA Moyen vs Contribution Publique par Pays
  labels:
    Average Contribution to Public Finances (% of GDP): Contribution publique (% PIB)
    Average ROA: ROA moyen (%)
  markdown: | 
    Ce graphique permet de visualiser les différences de modèles économiques entre pays. 
    On observe que certains pays comme le Canada ou l’Espagne affichent à la fois un ROA élevé et une forte contribution publique : ces pays hébergent des entreprises rentables et fiscalement contributives. 
    A l'inverse, l'Italie semble illustrer un modèle économique redistributif dans lequel des entreprises peu rentables soutiennent malgré tout significativement les recettes publiques.
    Cela met en évidence des arbitrages entre efficacité économique et politique fiscale.


plot_macro_correlation_heatmap:
  title: Matrice de corrélation entre indicateurs macroéconomiques
  markdown: |
   **Interprétation des coefficients :**  
   - **Revenue to GDP (%) vs Contribution Publique (% PIB) : +0.99**  
   ➤ Forte corrélation positive : Naturellement, plus les entreprises génèrent des revenus, plus elles paient d'impôts.

   - **Taux d’intérêt réel vs ROA moyen : +0.32**  
   ➤ Corrélation positive : Elle démontre une tendance des entreprises à être moins rentables lorsque les taux d’intérêt réels sont plus élevés.

    - **Taux d'intérêt réel vs Revenue to GDP (%) ou Contribution Publique : +0,46**  
   ➤ Corrélation positive : Une hausse des taux d'intérêts réels est associée à une hausse de la contribution des entreprises
     au PIB.

