folders:
  input_folder: input
  output_folder: output
  database_path: output.sqlite
  sqlite_table: financial_data

files_csv:
  source_financial_indicators: financial_indicators.csv
  source_largest_companies: largest_companies.csv
  merged_table: merged_table.csv

files_sql:
  source_financial_indicators: financial_indicators
  source_largest_companies: largest_companies
  merged_table: merged_table

export_final_results:
  financial_summary_stat: country_financial_summary
  firms_summary_stat: firms_financial_stat

largest_company_dataset:
  Rank: Rank

etl_main_parameters: ###a simplifier
  to_csv: true

columns:
  largest_companies:
    Rank : Rank
    Company : Company
    Industry : Industry
    Revenue in (USD Million) : Revenue
    Net Income in (USD Millions) : Net_Income
    Total Assest in (USD Millions) : Total_Asset
    Headquarters: Country

  largest_companies_aggregated:
    Headquarters: Country
    Revenue: Mean_Revenue
    Net_Income: Mean_Income
    Total_Asset: Mean_Total_Asset

rename_merged_table:
  Headquarters: Country
  Mean Revenue in (USD Million): Mean_Revenue
  Mean Net Income in (USD Millions): Mean_Income
  Mean Total Asset in (USD Millions): Mean_Total_Asset
  Interest Rate (%): Interest_Rate_Pct
  Inflation Rate (%): Inflation_Rate_Pct
  Stock Market Capitalization (% of GDP): Stock_market_Capitalization
  Banking Sector Assets (% of GDP): Banking_Sector_Asset
  Corporate Tax Rate (%): Corporate_Tax_Rate
  GDP (USD Trillions): GDP_USD_Trillion

drop_columns_largest_companies:
  - Rank

drop_columns_merged_table:
  - Country

countries_financial_summary_table:
  revenue_to_gdp: Revenue to GDP (%)
  real_interest_rate: Real Interest Rate (%)
  average_contrib_to_pub_fin: Average Contribution to Public Finances (% of GDP)
  average_roa: Average ROA

firms_financial_summary_table:
  company: Company
  asset_efficiency: Asset Efficiency
  return_on_assets: Return on Assets

data:
  Financial Summary Table: Financial Summary Table
  Firms Summary Table:  Firms Summary Table

streamlit:
  settings:
    page_title: Groupe_P
    layout: 'wide'
    initial_sidebar_state: auto #changer
    menu_items:
      Get Help: null
      Report a bug: null
      About: juste pour voir ce que ca fait

  widgets:
    selected_dataset:
      label: Choix des données
    options:
      Données par entreprise:
       - Top 10 ROA
       - ROA vs Efficiency
      Données par pays:
       - Contribution vs ROA
       - Matrice de corrélation macro
    select_box:
      label: Choix du graphique
    header:
      label: Visualisation de données
      divider: blue
    start_button:
      label: Afficher
    column:
      vertical_alignment: bottom
    expander:
      donnees_par_entreprise: Tableau - Données par entreprise #enlever les accents
      donnees_par_pays: Tableau - Données par pays
    slider:
      roa: Filtrage par ROA (%)
      efficiency: Filtrage par efficacité des actifs (%)


plot_roa_vs_efficiency:
  title: Rentabilité vs Efficacité des actifs (entreprises)
  labels:
    Asset Efficiency: Efficacité des Actifs
    Return on Assets: ROA (%)

plot_top10_roa:
  title: Top 10 entreprises par ROA
  col_y: Return on Assets
  labels:
    ROA arrondi: ROA (%)

plot_contribution_vs_roa:
  text: Country
  title: ROA moyen vs Contribution publique par pays
  labels:
    Average Contribution to Public Finances (% of GDP): Contribution publique (% PIB)
    Average ROA: ROA moyen (%)
  markdown: | 
    Ce graphique permet de visualiser les différences de modèles économiques entre pays. 
    On observe que certains pays comme la Chine ou les États-Unis bénéficient de champions nationaux très rentables mais peu taxés, 
    tandis que la France semble illustrer un modèle économique redistributif dans lequel des entreprises peu rentables soutiennent malgré tout significativement les recettes publiques. 
    Cela met en évidence des arbitrages entre efficacité économique et politique fiscale.

plot_macro_correlation_heatmap:
  title: Matrice de corrélation entre indicateurs macroéconomiques
  markdown: |
   **Interprétation des coefficients :**  
   - **Revenue to GDP (%) vs Contribution Publique (% PIB) : +0.90**  
   ➤ Des entreprises plus présentes dans l’économie génèrent logiquement plus de recettes fiscales pour l’État.  

   - **Taux d’intérêt réel vs ROA moyen : -0.44**  
   ➤  les taux d’intérêt réels sont élevés, les entreprises ont tendance à être moins rentables : taux réel élevé plus lourd ➤ coût du crédit plus lourd ➤ moins d'investissement et de croissance ➤ ROA plus faible.  

   - **Real Interest Rate (%) vs Revenue to GDP (%) ou Contribution Publique : corrélations proches de 0** 
   ➤ Il n’y a pas de lien direct entre les taux d’intérêt réels et la taille des entreprises dans l’économie (ou leur contribution fiscale).
 


